version: 2.1

executors:
  clojure:
    docker:
      - image: cimg/clojure:1.11

jobs:
  clj-kondo:
    docker:
      - image: cljkondo/clj-kondo:2024.09.27
    steps:
      - checkout
      - run: clj-kondo --lint .

  test-deps-plus:
    executor: clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-jars-{{ checksum "project.clj" }}
      - run: lein test-ci
      - store_test_results:
          path: target/test-results
      - store_artifacts:
          path: "target/coverage"
      - save_cache:
          key: v1-jars-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

  publish:
    executor: clojure
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-jars-{{ checksum "project.clj" }}
            - v1-jars
      - run:
          name: Download dependencies
          command: lein deps
      - run:
          name: Publish to clojars
          command: lein deploy

workflows:
  build-test:
    jobs:
      - clj-kondo
      - test-deps-plus
      - publish:
          context: clojars-publish
          requires:
            - test-deps-plus
          filters:
            branches:
              only:
                - main
